name: 'Install and Cache Node Modules'
description: 'Some description'
runs: 
  using: 'composite'
  steps:
      - name: Cache node modules
        id: cache-step
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: ${{ runner.os }}-cache-file-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-file-
            ${{ runner.os }}-
      - name: Displaycache
        run: echo '${{ toJson(steps.cache-step.outputs) }}' 
        shell: bash
      - name: Install node_modules
        run: npm install
        shell: bash