name: Docker
on: push
jobs: 
  test-docker-container:
    runs-on: ubuntu-latest
    services:
      customMysql:
        image: mysql
    container:
      image: node:21-alpine3.17
      env:
        NODE_ENV: development
      ports: 
        - 80
    steps:
      - name: Display service image
        run: echo '${{ toJson(job.services) }}'
      - name: Display node version
        run: node -v
      - name: Print new node version
        uses: docker://node:13
        with:
          args: -v