name: Eighteenth workflow
on: workflow_dispatch

jobs: 
  run-first-command:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Use custom action
          uses: ./.github/actions/cache-node-modules
          with:
            caching: 'false'
        