name: Eighth workflow
on: 
  workflow_dispatch: 
    inputs: 
      titleCustom: 
        description: Type the title
        type: string
        required: true
        default: "Hello world"
jobs: 
  success-command:
    runs-on: ubuntu-latest
    steps:
        - name: Event vars
          run: |
            echo "Title: ${{inputs.titleCustom}}"
