name: Eleventh workflow
on: [push]
env:
  WF_CUSTOM_VAR: WF 1

jobs: 
  run-first-command:
    runs-on: ubuntu-latest
    env:
      JOB_CUSTOM_VAR: JOB 1
    steps:
        - name: Set New VAr
          run: echo "NEW_CUSTOM_VAR=New Value" >> "$GITHUB_ENV" 
        - name: Event vars
          env:
            STEP_CUSTOM_VAR: STEP 1
            WF_CUSTOM_VAR: WF 2
          run: |
            echo $GITHUB_SHA
            echo '${{ github.ref }}'
            echo $WF_CUSTOM_VAR
            echo '${{ env.WF_CUSTOM_VAR }}'
            echo $JOB_CUSTOM_VAR
            echo $STEP_CUSTOM_VAR
            echo $NEW_CUSTOM_VAR
