name: Fifteeth workflow
on: [push]

jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
        - name: Math expressions
          run: expr 2 + 2 > math-result.txt
        - name: Upload result
          uses: actions/upload-artifact@v4
          with:
            name: math-result
            path: math-result.txt
  another-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
        - name: Download result
          uses: actions/download-artifact@v4
          with:
            name: math-result
        - name: Math Expression
          run: |
            value=`cat math-result.txt`
            expr $value \* 2 > math-result.txt
        - name: Delete Artifact
          uses: geekyeggo/delete-artifact@v5
          with:
            name: math-result
        - name: Upload result
          uses: actions/upload-artifact@v4
          with:
            name: math-result
            path: math-result.txt
  second-job:
    runs-on: ubuntu-latest
    needs: another-job
    steps:
        - name: Download result
          uses: actions/download-artifact@v4
          with:
            name: math-result
        - name: Print file
          run: |
            value=`cat math-result.txt`
            echo $value
         