name: Fifteeth workflow
on: [push]

jobs: 
  run-first-command:
    runs-on: ubuntu-latest
    steps:
        - name: Math expressions
          run: expr 2 + 2 > math-result.txt
        - name: Upload result
          uses: actions/upload-artifact@v4
          with:
            name: math-result
            path: math-result.txt
         
         
      