name: Fourteenth workflow
on: workflow_dispatch

jobs: 
  run-first-command:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Cache node modules
          id: cache-step
          uses: actions/cache@v3
          with: 
            path: ~/.npm
            key: "cache-file"
        - name: Displaycache
          run: echo '${{ toJson(steps.cache-step.outputs) }}'  
        - name: Install node_modules
          run: npm install    
         
      