name: Second workflow
on: push

jobs: 
  run-first-command:
    runs-on: ubuntu-latest
    steps:
        - name: Display node version on ubuntu
          run: node -v
  run-parrallel-command:
    runs-on: windows-latest
    steps:
        - name: Display node version on windows
          run: node -v
  run-second-command:
    runs-on: macos-latest
    needs: [run-first-command]
    steps:
        - name: Display node version on macos
          run: node -v   
     