name: Sixteenth workflow
on: [push]

jobs: 
  test-matrix-job:
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [12 ,14, 18]
        include: 
          - os: macos-latest
            node-version: 17
          - os: ubuntu-latest
            status: active
        exclude: 
          - os: ubuntu-latest
            node-version: 14
      max-parallel: 2  
      fail-fast: false
    steps:
        - run: node -v
        - uses: actions/setup-node@v3 
          with:
            node-version: ${{ matrix.node-version }}
        - run: node -v    
