name: Thirteenth workflow
on: [push]

jobs: 
  run-first-command:
    runs-on: ubuntu-latest
    steps:
        - name: First step
          id: first-step-1
          # run: sleep 30
          run: exit 1
        - name: Runs on cancelled
          if: ${{ cancelled() }}
          run: echo 'Runs on cancelled'
        - name: Runs on always
          if: ${{ always() }}
          run: echo 'Runs on always'
        - name: Runs on success
          if: ${{ success() }}
          run: echo 'Runs on success'
        - name: Runs on failure
          if: ${{ failure()  && steps.first-step.conclusion == 'failure' }}
          run: echo 'Runs on failure'
  run-second-command:
    runs-on: ubuntu-latest
    needs: run-first-command
    if: ${{ failure() }}
    steps:
        - name: Runs on cancelled
          run: echo 'Runs on cancelled'
