name: Thirteenth workflow
on: [push]

jobs: 
  run-first-command:
    runs-on: ubuntu-latest
    steps:
        - name: First step
          run: sleep 30
        - name: Runs on cancelled
          if: ${{ cancelled() }}
          run: echo 'Runs on cancelled'
        - name: Runs on always
          if: ${{ always() }}
          run: echo 'Runs on always'
        - name: Runs on success
          if: ${{ success() }}
          run: echo 'Runs on success'
        - name: Runs on failure
          if: ${{ failure() }}
          run: echo 'Runs on failure'
  run-second-command:
    runs-on: ubuntu-latest
    needs: run-first-command
    if: ${{ cancelled() }}
    steps:
        - name: Runs on cancelled
          run: echo 'Runs on cancelled'
