name: Third workflow
on: push

jobs: 
  run-first-command:
    runs-on: ubuntu-latest
    steps:
        - name: Display node version on ubuntu
          run: ls -la
        - uses: actions/checkout@v4    
        - name: List files
          run: ls -la
