name: Twelve workflow
on: [push]

jobs: 
  run-first-command:
    runs-on: ubuntu-latest
    steps:
        - name: Event vars
          run: |
            echo '${{ vars.STATUS }}'
            echo '${{ toJson(vars) }}'
            echo '${{ secrets.PASSWORD }}'
